name: Submit plugin

on:
    push:
        branches:
            - main # Adjust this branch name if needed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Post file to API
              uses: JantHsueh/upload-file-action@master
              with:
                url: "https://plugin-submit-poc.azurewebsites.net/api/submit?code=TNu57DRLYE4gGN6Oemj61PqqXsjlD0IYK2M2Ekwg9ai_AzFuoYz75A%3D%3D"
                fileForms: '{"File":"data/plugin.js"}'
                forms: '{}'
